config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :profile, only: :show

  resources :books do
    collection do
      get :search_cover
      get :proxy_image
      post :apply_cover
    end
  end

  resources :passwords, param: :token
  resources :loans
  resources :users
  resources :book_copies

  root "home#index"
  get "/home", to: "home#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <!-- Marca -->
    <a class="navbar-brand" href="<%= root_path %>">Biblioteca</a>

    <!-- Botão hamburger mobile -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Itens da navbar -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      <!-- Links à esquerda -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Início</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="loans">Empréstimos</a>
        </li>
        <% if current_user&.admin? %>
        <li class="nav-item">
          <a class="nav-link" href="books">Livros</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mais opções
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="users">Usuários</a></li>
          </ul>
        </li>
        <% end %>
      </ul>

      <!-- Botões à direita -->
      <div class="ms-auto">
        <% if logged_in? %>
          <%= button_to "Log out", session_path, method: :delete, class: "btn btn-outline-danger" %>          
        <% end %>
      </div>

      <div class="ms-2">
        <% if logged_in? %>
          <%= link_to "Meu usuário", profile_path, class: "nav-link" %>          
        <% end %>
      </div>


    </div>
  </div>
</nav>