config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :profile, only: :show

  resources :books do
    collection do
      get :search_cover
      get :proxy_image
      post :apply_cover
    end
  end

  resources :passwords, param: :token
  resources :loans
  resources :users
  resources :book_copies

  root "home#index"
  get "/home", to: "home#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/book_copy.rb
class BookCopy < ApplicationRecord
  belongs_to :book
  has_many :loans
end

app/controllers/book_copies_controller.rb
class BookCopiesController < ApplicationController
  before_action :set_book_copy, only: %i[ show edit update destroy ]

  # GET /book_copies or /book_copies.json
  def index
    @book_copies = BookCopy.all
  end

  # GET /book_copies/1 or /book_copies/1.json
  def show
  end

  # GET /book_copies/new
  def new
    @book_copy = BookCopy.new
  end

  # GET /book_copies/1/edit
  def edit
  end

  # POST /book_copies or /book_copies.json
  def create
    @book_copy = BookCopy.new(book_copy_params)

    respond_to do |format|
      if @book_copy.save
        format.html { redirect_to @book_copy, notice: "Book copy was successfully created." }
        format.json { render :show, status: :created, location: @book_copy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_copies/1 or /book_copies/1.json
  def update
    respond_to do |format|
      if @book_copy.update(book_copy_params)
        format.html { redirect_to @book_copy, notice: "Book copy was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @book_copy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_copies/1 or /book_copies/1.json
  def destroy
    @book_copy.destroy!

    respond_to do |format|
      format.html { redirect_to book_copies_path, notice: "Book copy was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_copy
      @book_copy = BookCopy.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def book_copy_params
      params.expect(book_copy: [ :heritage_code, :status, :book_id ])
    end
end

app/helpers/book_copies_helper.rb
module BookCopiesHelper
end

app/views/book_copies/_book_copy.html.erb
<div id="<%= dom_id book_copy %>">
  <div>
    <strong>Heritage code:</strong>
    <%= book_copy.heritage_code %>
  </div>

  <div>
    <strong>Status:</strong>
    <%= book_copy.status %>
  </div>

  <div>
    <strong>Book:</strong>
    <%= book_copy.book_id %>
  </div>

</div>

app/views/book_copies/_form.html.erb
<%= form_with(model: book_copy) do |form| %>
  <% if book_copy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_copy.errors.count, "error") %> prohibited this book_copy from being saved:</h2>

      <ul>
        <% book_copy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :heritage_code, style: "display: block" %>
    <%= form.text_field :heritage_code %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.checkbox :status %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/book_copies/edit.html.erb
<% content_for :title, "Editing book copy" %>

<h1>Editing book copy</h1>

<%= render "form", book_copy: @book_copy %>

<br>

<div>
  <%= link_to "Show this book copy", @book_copy %> |
  <%= link_to "Back to book copies", book_copies_path %>
</div>

app/views/book_copies/index.html.erb
<div class="container>
<p style="color: green"><%= notice %></p>

<% content_for :title, "Book copies" %>

<h1>Book copies</h1>

<div id="book_copies">
  <% @book_copies.each do |book_copy| %>
    <%= render book_copy %>
    <p>
      <%= link_to "Show this book copy", book_copy %>
    </p>
  <% end %>
</div>

<%= link_to "New book copy", new_book_copy_path %>
</div>

app/views/book_copies/new.html.erb
<% content_for :title, "New book copy" %>

<h1>New book copy</h1>

<%= render "form", book_copy: @book_copy %>

<br>

<div>
  <%= link_to "Back to book copies", book_copies_path %>
</div>

app/views/book_copies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_copy %>

<div>
  <%= link_to "Edit this book copy", edit_book_copy_path(@book_copy) %> |
  <%= link_to "Back to book copies", book_copies_path %>

  <%= button_to "Destroy this book copy", @book_copy, method: :delete %>
</div>